"""change subscribe

Revision ID: 470bded3788c
Revises: 732623edb6db
Create Date: 2020-11-03 12:23:48.873407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470bded3788c'
down_revision = '732623edb6db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribes', sa.Column('emaill', sa.String(length=100), nullable=True))
    op.drop_constraint('subscribes_email_key', 'subscribes', type_='unique')
    op.create_unique_constraint(None, 'subscribes', ['emaill'])
    op.drop_column('subscribes', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribes', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subscribes', type_='unique')
    op.create_unique_constraint('subscribes_email_key', 'subscribes', ['email'])
    op.drop_column('subscribes', 'emaill')
    # ### end Alembic commands ###
