"""edit column

Revision ID: 49be29356907
Revises: 03561de41795
Create Date: 2020-11-03 13:01:16.804234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49be29356907'
down_revision = '03561de41795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
