"""add column user

Revision ID: 4f9a6f11e24c
Revises: fad9e442b4b3
Create Date: 2020-11-02 15:41:40.558066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f9a6f11e24c'
down_revision = 'fad9e442b4b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('time_post', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'time_post')
    # ### end Alembic commands ###
