"""add class subscribe

Revision ID: 639ddf31be51
Revises: 9595ddcd3d00
Create Date: 2020-11-02 12:52:38.710251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639ddf31be51'
down_revision = '9595ddcd3d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('blogs', sa.Column('title', sa.String(length=255), nullable=False))
    op.drop_column('blogs', 'blog_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('blogs', 'title')
    op.drop_table('subscribes')
    # ### end Alembic commands ###
