"""add column

Revision ID: 732623edb6db
Revises: b915d075cdbc
Create Date: 2020-11-02 20:12:21.898275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732623edb6db'
down_revision = 'b915d075cdbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_file', sa.String(length=70), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_file')
    # ### end Alembic commands ###
