"""add category

Revision ID: b915d075cdbc
Revises: 4f9a6f11e24c
Create Date: 2020-11-02 17:33:42.723439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b915d075cdbc'
down_revision = '4f9a6f11e24c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('category', sa.String(), nullable=True))
    op.create_index(op.f('ix_blogs_category'), 'blogs', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blogs_category'), table_name='blogs')
    op.drop_column('blogs', 'category')
    # ### end Alembic commands ###
