"""add columns

Revision ID: fad9e442b4b3
Revises: 639ddf31be51
Create Date: 2020-11-02 15:00:10.849660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad9e442b4b3'
down_revision = '639ddf31be51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribes', sa.Column('email', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'subscribes', ['email'])
    op.add_column('users', sa.Column('bio', sa.String(length=5000), nullable=True))
    op.add_column('users', sa.Column('password_secure', sa.String(length=5000), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'password_secure')
    op.drop_column('users', 'bio')
    op.drop_constraint(None, 'subscribes', type_='unique')
    op.drop_column('subscribes', 'email')
    # ### end Alembic commands ###
